[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker    = "ldproxy"
rustflags = ["-C", "default-linker-libraries"]

[unstable]
build-std          = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[env]
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "./sdkconfig.defaults", relative = true }
